### ISSUE TITLE
no configuration file provided: not found

### ISSUE THREAD

**Issue by DrFriendlyFire** [kaysond/docker-terraria#10]
I used this command to install the server. I was told I should not give it root privileges, I will fix that later once I figure out why it is not working. 

docker run -itd --name=terraria -e PUID=1000 -e PGID=1000 -p 7779:7777 -v /DATA/AppData/Terraria/world:/world -v /DATA/AppData/Terraria/config:/config kaysond/docker-terraria

When I run docker-compose up -d it says "no configuration file provided: not found" however I made sure that the file is in the path: /DATA/AppData/Terraria/config and it is configured as: 

world=/DATA/AppData/Terraria/world/World.wld
worldpath=/DATA/AppData/Terraria/world
autocreate=2

Any help is greatly appreciated.

**Comment by kaysond** [comment]
To clarify - you should **either** run the `docker run` command, **or** create the `docker-compose.yml` file following the example, then run `docker compose up -d`. 

That error message you're seeing isn't the Terraria server. It's `docker compose` complaining that you don't have a `docker-compose.yml` file. docker compose is generally recommended since you can save the configuration in a file and not have to remember the exact command you used.

Assuming your world file is at `/DATA/AppData/Terraria/world/World.wld`, your `docker run` command is correct, but your `serverconfig.txt` needs to point to the paths as they're seen from inside the container, not from the host, meaning: `world=/world/World.wld` and `worldpath=/world`. That config file should live at `/DATA/AppData/Terraria/config/serverconfig.txt` on your host.

If you're not familiar with how docker's bind mounts work, you can check out the docs [here](https://docs.docker.com/storage/bind-mounts/)

**Comment by kaysond** [comment]
If you wanted to use docker compose, your file would look like:

```yml
services:
  terraria:
    container_name: terraria
    image: kaysond/docker-terraria
    environment:
      PUID: "1000"
      PGID: "1000"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 7779:7777
    volumes:
      - /DATA/AppData/Terraria/world:/world
      - /DATA/AppData/Terraria/config:/config
```

and same `serverconfig.txt` as mentioned above.
