### ISSUE TITLE
Startconfig not working

### ISSUE THREAD

**Issue by blackerking** [kaysond/docker-terraria#5]
Hey,

the startconfig doesn't work properly. It seems you used the world folder twice and in the end the container has no rights to write the file.
This works for me:

```
world=World.wld
worldpath=/world
autocreate=1
worldname=Terraria
```

**Comment by kaysond** [comment]
Can you explain more? I have my container running with `world=/world/World.wld`  and it runs just fine.

Can you post your `run` command or `docker-compose.yml` file?

**Comment by blackerking** [comment]
It stops and says that the world cannot saved because of missing rights.
I can't also access the folder (No write permission).

**Comment by kaysond** [comment]
That's probably not an issue with the config. You have to specify a uid and gid for the process to run as via the environment variables listed in the README. If you don't, it'll run as 911:911. If that user/group doesn't have permissions in your volume, then it won't be able to run.

Can you post the run command or docker-compose file youre using?

**Comment by blackerking** [comment]
I've used the docker-compose file with a .env file. The same for other container. I will post this later.
But I think it is strange that the world folder is not created in your shell scripts, but your config.

**Comment by blackerking** [comment]
docker-compose.yml
```
##Terraria Game-Server
version: "2.1"
services:
  terraria:
    image: kaysond/docker-terraria
    container_name: terraria
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - ${FILEPLACE}/terraria/world:/world
        - ${FILEPLACE}/terraria/config:/config
    ports:
        - 7777:7777
    restart: always
    stdin_open: true
    tty: true
```
.env

```
PUID=1002
PGID=100
FILEPLACE=/srv/dev-disk-by-label-Daten/dockerfolder
```
